### ISSUE TITLE
Handle different polarizations in a robust way

### ISSUE THREAD

**Issue by adampbeardsley** [dannyjacobs/uvlabeller#1]
I tried opening a file that doesn't have polarization 'xx', and it crashed hard. Looks like xx is hard coded.

I think we want to make another selection box for the polarization because in principle multiple pols can (and will) be in a file.

**Comment by HalcyonAura** [comment]
Solved with this [commit!](https://github.com/dannyjacobs/uvlabeller/commit/61470b58420e321c23bb831a9586005b338658d0)
